from django.contrib import admin
from django.urls import path
from MySQL_CRUD import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.home,name="Home"), #localhost:8000
    path('hip/',views.hip),
    path('knee/',views.knee),
    path('shoulder/',views.shoulder),
    path('search/',views.search),
    path('compound/',views.compound),
    path('closefracture/',views.closefracture),
    path('compartment/',views.compartment),
    path('crush/',views.crush),
    path('fat/',views.fat),
    path('fracture/',views.fracture),
    path('myositis/',views.myositis),
    path('nerveinjuries/',views.nerveinjuries),
    path('pathological/',views.pathological),
    path('stress/',views.stress),
    path('pyogenic/',views.pyogenic),
    path('volk/',views.volk),
    path('Trigger/',views.Trigger),                      
    path('tension/',views.tension),
    path('Tennis/',views.Tennis),
    path('tb/',views.tb),
    path('supre/',views.supre),
    path('spon/',views.spon),  
    path('sp/',views.sp),
    path('slipp/',views.slipp),
    path('shoul/',views.shoul),
    path('scan/',views.scan),
  path('rup/',views.rup),
  path('ring/',views.ring),
  path('recurrent/',views.recurrent),
  path('radio/',views.radio),
  path('paget/',views.paget),
  path('osteo/',views.osteo),
  path('ole/',views.ole),
  path('monteggia/',views.monteggia),
  path('manage/',views.manage),
  path('mallet/',views.mallet),
  path('ideal/',views.ideal),
  path('green/',views.green),
  path('gibbus/',views.gibbus),
  path('giant/',views.giant),
  path('frozen/',views.frozen),
  path('external/',views.external),
  path('Dupuytren/',views.Dupuytren),
  path('colles/',views.colles),
  path('codman/',views.codman),
  path('clinical/',views.clinical),
  path('carpel/',views.carpel),
  path('brodie/',views.brodie),
  path('bone/',views.bone),
   path('medical/',views.medical),
  path('bifida/',views.bifida),
  path('aval/',views.aval),
    path('poris/',views.poris),
    path('hipfracture/',views.hipfracture),
  path('de/',views.de),
  path('hk/',views.hk),
  path('h1/',views.h1),
  path('hips/',views.hips),
  path('sandbox/',views.sandbox),
  path('fractureofpetalla/',views.fractureofpetalla),
  path('stick/',views.stick),
   path('age/',views.age),
    path('boneandjoints/',views.boneandjoints),
     path('bonecysts/',views.bonecysts),
      path('upp/',views.upp),
       path('low/',views.low),
        path('mis/',views.mis),
          path('spin/',views.spin),
          path('princ/',views.princ),
          path('back/',views.back),
           path('pain/',views.pain),
    path('causes/',views.causes),
     path('arth/',views.arth),
          path('bur/',views.bur),
               path('fib/',views.fib),
                    path('foot/',views.foot),
                         path('hand/',views.hand),
                              path('ky/',views.ky),
                                   path('neck/',views.neck),
                                        path('scol/',views.scol),
                                             path('soft/',views.soft),
                                                 path('trial/',views.trial),
                                                      path('ortho/',views.ortho),
                                                  path('gto/',views.gto),
                                                
  
]
  